USE [master]
GO
/****** Object:  Database [ACMESOFTIntegration]    Script Date: 01-Apr-22 12:33:19 PM ******/
CREATE DATABASE [ACMESOFTIntegration]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ACMESOFTIntegration', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ACMESOFTIntegration.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ACMESOFTIntegration_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ACMESOFTIntegration_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ACMESOFTIntegration] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ACMESOFTIntegration].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ACMESOFTIntegration] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ACMESOFTIntegration] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ACMESOFTIntegration] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ACMESOFTIntegration] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ACMESOFTIntegration] SET ARITHABORT OFF 
GO
ALTER DATABASE [ACMESOFTIntegration] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ACMESOFTIntegration] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ACMESOFTIntegration] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ACMESOFTIntegration] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ACMESOFTIntegration] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ACMESOFTIntegration] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ACMESOFTIntegration] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ACMESOFTIntegration] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ACMESOFTIntegration] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ACMESOFTIntegration] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ACMESOFTIntegration] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ACMESOFTIntegration] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ACMESOFTIntegration] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ACMESOFTIntegration] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ACMESOFTIntegration] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ACMESOFTIntegration] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [ACMESOFTIntegration] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ACMESOFTIntegration] SET RECOVERY FULL 
GO
ALTER DATABASE [ACMESOFTIntegration] SET  MULTI_USER 
GO
ALTER DATABASE [ACMESOFTIntegration] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ACMESOFTIntegration] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ACMESOFTIntegration] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ACMESOFTIntegration] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ACMESOFTIntegration] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ACMESOFTIntegration] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ACMESOFTIntegration', N'ON'
GO
ALTER DATABASE [ACMESOFTIntegration] SET QUERY_STORE = OFF
GO
USE [ACMESOFTIntegration]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 01-Apr-22 12:33:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Employee]    Script Date: 01-Apr-22 12:33:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee](
	[EmployeeId] [int] IDENTITY(1,1) NOT NULL,
	[PersonId] [int] NULL,
	[EmployeeNumber] [nvarchar](16) NOT NULL,
	[EmployeeDate] [datetime2](7) NOT NULL,
	[TerminationDate] [datetime2](7) NULL,
	[IsDeleted] [bit] NULL,
 CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED 
(
	[EmployeeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Person]    Script Date: 01-Apr-22 12:33:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Person](
	[PersonId] [int] IDENTITY(1,1) NOT NULL,
	[LastName] [nvarchar](128) NULL,
	[FirstName] [nvarchar](128) NULL,
	[BirthDate] [datetime2](7) NULL,
	[IsDeleted] [bit] NULL,
 CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED 
(
	[PersonId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 01-Apr-22 12:33:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [nvarchar](128) NULL,
	[Password] [nvarchar](128) NULL,
	[IsAdmin] [bit] NULL,
	[IsDeleted] [bit] NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_Employee_PersonId]    Script Date: 01-Apr-22 12:33:19 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Employee_PersonId] ON [dbo].[Employee]
(
	[PersonId] ASC
)
WHERE ([PersonId] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Employee]  WITH CHECK ADD  CONSTRAINT [FK_Employee_Person_PersonId] FOREIGN KEY([PersonId])
REFERENCES [dbo].[Person] ([PersonId])
GO
ALTER TABLE [dbo].[Employee] CHECK CONSTRAINT [FK_Employee_Person_PersonId]
GO
USE [master]
GO
ALTER DATABASE [ACMESOFTIntegration] SET  READ_WRITE 
GO
